service: cvs-tsk-update-store



plugins:
  - serverless-plugin-typescript
    # .dotenv is not currently supported so we use this serverless plugin for env configuration
  - serverless-dotenv-plugin
    # https://github.com/serverless-heaven/serverless-webpack/tree/master/examples
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-tracing

  provider:
  name: aws
  runtime: nodejs10.x
  tracing:
    lambda: "true"
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  main:
    handler: src/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:region:XXXXXX:update-store-q
          batchSize: 10

custom:
  serverless-offline:
    port: 3012
